### ISSUE TITLE
S2583 FP with String.IsNullOrWhiteSpace

### ISSUE THREAD

**Issue by mitchello** [SonarSource/sonar-dotnet#2620]
### Description

After an analysis, a bug is raised with the following message:
"Change this condition so that it does not always evaluate to 'true'"
It seems that the scanner consider the same string.IsNullOrEmpty and string.IsNullOrWhiteSpace.

### Repro steps

```
if (String.IsNullOrWhiteSpace(someString))
{
	if (someString== null)
	{
		throw new ArgumentNullException(nameof(someString), 
			$"The parameter {nameof(someString)} is mandatory but a null value was provided.");
	}
	throw new ArgumentException($"The {nameof(someString)} provided was empty or just white space(s).", 
		nameof(someString));
}
```

### Expected behavior

No error in the analysis as null is different of white space.

### Actual behavior

Change this condition so that it does not always evaluate to 'true' (line if(someString == null))

### Related information

* SonarC# Version 7.15 (build 8572)
* SonarQube Version 7.9.1.27448

**Comment by andrei-epure-sonarsource** [comment]
thanks @mitchello 
I cannot repro, this most likely got fixed in #2576 which was released in [7.16](https://github.com/SonarSource/sonar-dotnet/releases)

**Comment by ssougnez** [comment]
I'm reopening this one as I still have the issue with the version 7.6:

![image](https://user-images.githubusercontent.com/10199821/109820173-0e4d7400-7c35-11eb-933f-8444a4a13cc6.png)

Cheers

**Comment by pavel-mikula-sonarsource** [comment]
Hi @ssougnez,

Please create a new issue with full information if you can reproduce it with the latest version of our plugin - 8.23 Nuget, SonarCloud or SonarQube 8.9
