### ISSUE TITLE
S5766 should only be available when running in batch analysis mode

### ISSUE THREAD

**Issue by mattzink** [SonarSource/sonar-dotnet#3421]
### Description

We are seeing many false-positives for the new S5766 rule (Deserializing objects without performing data validation is security-sensitive) and would like to disable it, but our attempts to suppress the rule in source (via `#pragma warning disable S5766`) or reconfigure it's severity in our ruleset file have no effect.

### Repro steps

1) Create an instance of S5766
2) Add `#pragma warning disable S5766` to the top of the file

### Known workarounds

None

### Related information

* C#/VB.NET Plugins Version: 8.9.0.19135
* Visual Studio Version: 16.6.3
* MSBuild / dotnet version: .NET Core SDK 3.1.102
* Operating System: Windows 10

**Comment by andrei-epure-sonarsource** [comment]
Hi @mattzink . Thanks a lot for raising this issue.

Could you share what FPs you are seeing for this rule?

**Comment by andrei-epure-sonarsource** [comment]
Actually, coming back - @mattzink , this is a security hotspot rule and it should not be running when consuming the nuget or using SonarLint.

This should only run during a build with the Scannner for MSBuild + SonarQube/SonarCloud.

How are you consuming the plugin?

**Comment by mattzink** [comment]
> Could you share what FPs you are seeing for this rule?

Well the rule's generalization that any conditional checks that involve constructor parameters == validation is flawed logic to me. For example, in one case we pass the constructor parameter to an auditing service if it's not null. We don't want that to happen every time the object is deserialized.

> How are you consuming the plugin?

We're are consuming the analyzer as a NuGet package only.

**Comment by andrei-epure-sonarsource** [comment]
Thanks for the feedback @mattzink !

This security hotspot shouldn't be available via the nuget package consumption, that's a flaw on our side (cc @costin-zaharia-sonarsource ).

**Comment by costin-zaharia-sonarsource** [comment]
Hi @mattzink,

Thanks for the feedback!

The fix was merged and the rule will not execute anymore when using Sonar Lint (hot spots are meant to be run only by the [scanner](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/)). This will be available in the next release, which planned on July 17th.

**Comment by mattzink** [comment]
I am still seeing this analyzer run with Sonar 8.10, so it appears this issue is not yet fixed.

**Comment by costin-zaharia-sonarsource** [comment]
> I am seeing S5766 rule still run with Sonar 8.10 via nuget, so it appears this issue is not yet fixed.

You're right, the problem is still reproducible. Sorry for that. 

The fix is now in review and will be available in the next version.
